// <auto-generated />
namespace Trash_collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class madefewchangesincustomermodelandaddedpropertyforphonenumbers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(madefewchangesincustomermodelandaddedpropertyforphonenumbers));
        
        string IMigrationMetadata.Id
        {
            get { return "201811011856175_made few changes in customer model and added property for phone numbers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
