// <auto-generated />
namespace Trash_collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addedanemailidforcalendermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedanemailidforcalendermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811021253442_added an email id for calender model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
