// <auto-generated />
namespace Trash_collection.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class updatedpropertiesforpickupsincalendermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedpropertiesforpickupsincalendermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "201811021249546_updated properties for pickups in calender model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
